app:
# Drivers: sqlite3, mysql
  store-driver: "sqlite3"
  store-options:
    host:
    port:
    user:
    password:
    name:
  units:
    telegram:
      enabled: true
      token: "some-token"
profiling:
  enabled: false
  file: "cpu.prof"